// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkjlozotevyvqltdxebp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZramxvem90ZXZ5dnFsdGR4ZWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjEwOTYsImV4cCI6MjA2NzUzNzA5Nn0.kDnQz-8ywzubig28l01A_eSuRfh4eppPH6Tb9_MbtyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});